spring:
  cloud:
   gateway:
     routes:
       - id: microservice-a
         uri: lb://MICROSERVICE-A
         predicates:
           - Path=/service-a/**	   
       - id: microservice-b
         uri: lb://MICROSERVICE-B
         predicates:
           - Path=/service-b/**
       - id: microservice-c
         uri: lb://MICROSERVICE-C
         predicates:
           - Path=/service-c/**