spring.application.name=microservice-b
server.port=0

company.name=Cognizant
company.location=Coimbatore

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost